### ISSUE TITLE
Dropping support for Backbone, whart's the purpose of that?

### ISSUE THREAD

**Issue by ajstrand** [marionettejs/marionette#21]
The previous backbone-marionette repo mentioned the desire to drop support for Backbone. 

What's the purpose of that move?

Is there a desire to integrate with frameworks like React/Svelte/Vue in the future?

**Comment by paulfalgout** [comment]
This library would not drop support for Backbone, but just remove it as a dependency.  I'm not sure what the point of integrating Marionette with React or Vue would be but you could certainly use a different data layer if you wanted.  Marionette has already removed jQuery as a dependency such that alternate renders can be used to modify the DOM.  I suspect many people will continue to use backbone with marionette.  But with v5 you could use `fetch` and and simple object or array if desired.
